language: ruby
rvm:
- 2.3.0

script:
  - ./scripts/deploy

branches:
  only:
  - develop

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - USERNAME: Travis CI
  - EMAIL: paul.dijou@gmail.com

sudo: false # route your build to the container-based infrastructure for a faster build
