title: Paul Dijou
default_page_title: Computer Science Engineer
use_dashboard: true
home_url: /
home_label: Home
default_summary_size: 50
max_url_label_size: 30
blog_prefix: /blog
scroll_spy_offset: 60
blog_assets_url: /blog/assets
projects_assets_url: /projects/assets
carousel_interval: 4000

social_identities:
  twitter: paul_dijou
  github: pauldijou
  google_plus: 102994553784447043819
  klout: paul_dijou

github_fork:
  render: true
  url: http://github.com/pauldijou
  position: fixed
  z_index: 5000
  top: 0
  color: red
  align: left
  alt: Fork me on GitHub
  img_prefix: https://s3.amazonaws.com/github/ribbons/
  hidden_desktop: false
  hidden_tablet: true
  hidden_phone: true

profiles:
  development:
    root_url: http://localhost:4242
    base_url: http://localhost:4242
    disqus: pauldijou
    disqus_generate_id: true
    disqus_developer: true
  production:
    root_url: http://pauldijou.fr
    base_url: http://pauldijou.fr
    google_analytics: UA-25058935-1
    disqus: pauldijou
    disqus_generate_id: true
    deploy:
      host: github_pages
      branch: master

github_fork_images:
  red:
    left: forkme_left_red_aa0000.png
    right: forkme_right_red_aa0000.png
  green:
    left: forkme_left_green_007200.png
    right: forkme_right_green_007200.png
  black:
    left: forkme_left_darkblue_121621.png
    right: forkme_right_darkblue_121621.png
  orange:
    left: forkme_left_orange_ff7600.png
    right: forkme_right_orange_ff7600.png
  gray:
    left: forkme_left_gray_6d6d6d.png
    right: forkme_right_gray_6d6d6d.png
  white:
    left: forkme_left_white_ffffff.png
    right: forkme_right_white_ffffff.png